Repository moka-rs/moka, pull requests merged in 2021-09, with the labels that each got.

#30 Add examples to the doc for `get_or_insert_with` and `get_or_try_insert_with` methods
  .vscode/settings.json
  CHANGELOG.md
  Cargo.toml
  src/future/cache.rs
  src/future/value_initializer.rs
  src/sync/cache.rs
  src/sync/value_initializer.rs
Labels: documentation

#32 Add `Send` and `'static` bounds to the init futures of `get_or_(try_)insert_with`
  .github/workflows/CI.yml
  .vscode/settings.json
  CHANGELOG.md
  Cargo.toml
  README.md
  src/future/cache.rs
  src/lib.rs
  tests/ui/future/get_with_non_send_future.rs
  tests/ui/future/get_with_non_send_future.stderr
  tests/ui/future/get_with_non_static_future.rs
  tests/ui/future/get_with_non_static_future.stderr
Labels: bug

#33 Downgrade crossbeam-epoch from v0.9.x to v0.8.x
  CHANGELOG.md
  Cargo.toml
  README.md
Labels: bug

#37 Remove the `Error` bound from `get_or_try_insert_with` method
  CHANGELOG.md
  src/future/cache.rs
  src/future/value_initializer.rs
  src/sync/cache.rs
  src/sync/value_initializer.rs
Labels: enhancement

#39 Support Linux on MIPS and ARMv5TE
  .github/workflows/CI.yml
  .vscode/settings.json
  CHANGELOG.md
  Cargo.toml
  README.md
  src/common.rs
  src/common/thread_pool.rs
  src/common/time_compat.rs
  src/common/time_quanta.rs
  src/future/cache.rs
  src/lib.rs
  src/sync.rs
  src/sync/base_cache.rs
  src/sync/cache.rs
  src/sync/invalidator.rs
  src/sync/segment.rs
  src/unsync.rs
  src/unsync/cache.rs
Labels: enhancement

#46 Handle panic in the `init` closure/future of `get_or_insert_with` and `get_or_try_insert_with`
  CHANGELOG.md
  Cargo.toml
  src/future/cache.rs
  src/future/value_initializer.rs
  src/sync/cache.rs
  src/sync/value_initializer.rs
Labels: bug

#47 Replace futures with futures-util
  Cargo.toml
  src/future/cache.rs
  src/future/value_initializer.rs
  tests/runtime_actix_rt1.rs
  tests/runtime_actix_rt2.rs
  tests/runtime_async_std.rs
  tests/runtime_tokio.rs
Labels: enhancement
