Repository moka-rs/moka, pull requests merged in 2023-09, with the labels that each got.

#316 Remove the thread pool from `sync` caches
  .cirrus.yml-DISABLED
  .github/workflows/CI.yml
  .github/workflows/Kani.yml
  .github/workflows/Miri.yml
  .github/workflows/Skeptic.yml
  CHANGELOG.md
  Cargo.toml
  MIGRATION-GUIDE.md
  README.md
  examples/eviction_listener.rs
  src/cht.rs
  src/cht/segment.rs
  src/common.rs
  src/common/builder_utils.rs
  src/common/concurrent.rs
  src/common/concurrent/constants.rs
  src/common/concurrent/housekeeper.rs
  src/common/concurrent/thread_pool.rs
  src/common/concurrent/unsafe_weak_pointer.rs
  src/future/builder.rs
  src/future/cache.rs
  src/lib.rs
  src/notification.rs
  src/notification/notifier.rs
  src/sync/builder.rs
  src/sync/cache.rs
  src/sync/segment.rs
  src/sync_base/base_cache.rs
  src/sync_base/invalidator.rs
Labels: enhancement

#318 Reenable the `sync` feature for doc.rs
  Cargo.toml
  README.md
Labels: documentation

#319 Remove a duplicate paragraph from the migration guide
  MIGRATION-GUIDE.md
Labels: documentation

#323 Better async waiting for when the write op channel is full
  Cargo.toml
  src/future.rs
  src/future/base_cache.rs
  src/future/cache.rs
Labels: enhancement

#324 Get the last modified time for upsert after acquiring key level lock
  CHANGELOG.md
  src/future/base_cache.rs
  src/policy.rs
  src/sync_base/base_cache.rs
Labels: bug, documentation

#325 typo in weblink
  README.md
Labels: documentation
